from .checkpoints import Neo4jCheckpointStore as Neo4jCheckpointStore
from pathlib import Path
from typing import Any, Mapping, Sequence
from uuid import UUID
from .connector import (
    CollectedBatch as CollectedBatch, CollectionContext as CollectionContext,
    CollectionError as CollectionError, CollectionLimits as CollectionLimits,
    Connector as Connector,
)
from .inputs import ConnectorEntity as ConnectorEntity, ExistingSnapshotInput as ExistingSnapshotInput, SnapshotInput as SnapshotInput
from .journal import CheckpointStore as CheckpointStore, JournalError as JournalError, PreparedRun as PreparedRun, RunJournal as RunJournal

class ConfigurationError(ValueError): ...
class InputValidationError(ValueError):
    run_id: str
class EngineClosedError(RuntimeError): ...
class ForkedEngineError(RuntimeError): ...
class IngestionError(RuntimeError):
    outcome: dict[str, Any]
    run_id: str
class IngestionInterrupted(KeyboardInterrupt):
    outcome: dict[str, Any]
    run_id: str
class IngestionResult(dict[str, Any]):
    @property
    def complete(self) -> bool: ...
    @property
    def run_id(self) -> UUID: ...
    def require_complete(self) -> IngestionResult: ...
class CancellationToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def cancelled(self) -> bool: ...
class Limits:
    def __init__(self, max_request_bytes: int = ..., max_response_bytes: int = ..., max_snapshot_bytes: int = ...,
                 max_depth: int = ..., max_snapshots: int = ..., max_entities: int = ...,
                 workers: int = ..., admitted_calls: int = ..., blocking_threads: int = ...) -> None: ...
class Engine:
    def __init__(self, config: Mapping[str, Any], *, connectors: Sequence[Any] = ...,
                 ontology: Mapping[str, Any] | None = ..., ontology_org_id: str | None = ...,
                 limits: Limits = ..., profiles: dict[str, ProfileRef | dict[str, Any]] | None = ...,
                 connector_profiles: dict[str, ProfileRef | dict[str, Any]] | None = ...) -> None: ...
    def ingest(self, snapshots: Sequence[dict[str, Any] | SnapshotInput | ExistingSnapshotInput], *, org_id: str, run_id: UUID | None = ...,
               cancellation: CancellationToken | None = ..., timeout: float | None = ...,
               trace_id: str | None = ..., profiles: dict[str, ProfileRef | dict[str, Any]] | None = ...) -> IngestionResult: ...
    def register_profile(self, document: dict[str, Any], *, org_id: str, timeout: float | None = ..., cancellation: CancellationToken | None = ...) -> dict[str, Any]: ...
    def get_profile(self, profile: ProfileRef | dict[str, Any], *, org_id: str, timeout: float | None = ..., cancellation: CancellationToken | None = ...) -> dict[str, Any] | None: ...
    def list_profiles(self, *, org_id: str, after: ProfileRef | dict[str, Any] | None = ..., limit: int = ..., timeout: float | None = ..., cancellation: CancellationToken | None = ...) -> dict[str, Any]: ...
    def decide(self, state: Any, questions: dict[str, Any], *, timeout: float | None = ...) -> dict[str, Any]: ...
    def checkpoint_store(self, *, org_id: str, namespace: str) -> Neo4jCheckpointStore: ...
    def prepare(self, connector: str, context: CollectionContext, *, journal: RunJournal,
                cancellation: CancellationToken | None = ..., timeout: float | None = ...,
                checkpoint_store: Neo4jCheckpointStore | None = ...) -> PreparedRun: ...
    def prepare_thread_recovery(self, original: PreparedRun, *, journal: RunJournal, run_id: UUID | None = ...) -> PreparedRun: ...
    def prepare_saga_recovery(self, original: PreparedRun, *, journal: RunJournal, run_id: UUID | None = ...) -> PreparedRun: ...
    def replay(self, prepared: PreparedRun, *, journal: RunJournal,
               cancellation: CancellationToken | None = ..., timeout: float | None = ...) -> IngestionResult: ...
    def learn_rules(self, source: str, *, org_id: str, auto_promote: bool = ...,
                    run_id: UUID | None = ..., cancellation: CancellationToken | None = ...,
                    timeout: float | None = ...) -> IngestionResult: ...
    def list_rules(self, source: str, *, org_id: str, status: str | None = ...,
                   run_id: UUID | None = ..., cancellation: CancellationToken | None = ...,
                   timeout: float | None = ...) -> IngestionResult: ...
    def rebuild_communities(self, *, org_id: str, namespace: str, run_id: UUID | None = ...,
                           cancellation: CancellationToken | None = ..., timeout: float | None = ...) -> IngestionResult: ...
    def summarize_thread(self, *, org_id: str, namespace: str, thread: dict[str, str],
                       run_id: UUID | None = ..., cancellation: CancellationToken | None = ..., timeout: float | None = ...) -> IngestionResult: ...
    def summarize_saga(self, *, org_id: str, namespace: str, saga: dict[str, str],
                       run_id: UUID | None = ..., cancellation: CancellationToken | None = ..., timeout: float | None = ...) -> IngestionResult: ...
    def close(self) -> None: ...
    def __enter__(self) -> Engine: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
class TelemetryHandle:
    def close(self) -> None: ...
def configure_telemetry(config: Mapping[str, Any]) -> TelemetryHandle: ...

class ProfileRef:
    profile_id: str
    revision: int
    def __init__(self, profile_id: str, revision: int) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
class OperationError(RuntimeError):
    outcome: dict[str, Any]
def load_profile(path: str | Path) -> dict[str, Any]: ...
